AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.jobportal::jobportal-lambda-v1
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  JobportalLambdaV1Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.jobportal.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  JobportalLambdaV1Api:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: JobportalLambdaV1Api
